### PR TITLE
Aarch64 address lowering

### PR DESCRIPTION
**Pull request by adinn**
Here's a new pull request for the AArch64 address lowering patch rebased against the latest upstream head.

### CODE REVIEW

**Comment by adinn** [comment]
I fixed the eclipse style errors and also rebased and resolved the conflict with recent changes to HotSpotSuitesProvider. I have still to verify that this build works correctly.

**Comment by adinn** [comment]
I have tested this build and it runs everything as expected. So, I believe it is ready for a merge into the master tree.

**Comment by tkrodriguez** [comment]
I'm running it through the gate now.  I'll update you if there's anything to be fixed beyond trivial formatting stuff.

**Comment by tkrodriguez** [comment]
I fixed some other style issues that weren't caught by the travis gate.  dead imports, unused methods and arguments.  I also factored out the old address handling into a non-platform dependent AddressLoweringHotSpotSuitesProvider to make it easier to reuse.

**Comment by adinn** [comment]
That's all fine by me.

Is it possible to pull this into the main trunk now?

**Comment by dougxc** [comment]
It's currently moving through the internal integration process and should land on github in the next 48 hours.

**Pull request merged**
