### PR TITLE
fix AArch64 stack saves and copies

### PR DESCRIPTION
**Pull request by adinn**
This patch fixes the problem reported here: https://github.com/graalvm/graal/issues/236

The patch includes a unit test which manifest the problem and confirms the fix as described in the issyue mentioned above.

### CODE REVIEW

**Comment by dougxc** [comment]
lgtm

**Comment by dougxc** [comment]
I've started the process for integrating this. I reverted the change in `JVMCIVersionCheck` as it forces us to prepare a 177 binary internally. The only change really needed is in `.travis.yml`.

**Comment by adinn** [comment]
Ok, great. Thanks very much.

**Comment by adinn** [comment]
I have deleted the unused var stackCopy. I did not detect this error when I ran the eclipseformat command. Is this the right command? Do I need to provide some other arguments to mx?

**Comment by dougxc** [comment]
This should do it: `mx clean; mx build --jdt /path/to/ecj-4.5.1.jar --warning-as-error`
You can get ecj-4.5.1.jar [here](http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.1-201509040015/).

**Pull request merged**
