### PR TITLE
Aarch64 address lowering

### PR DESCRIPTION
**Pull request by adinn**
I have retested this patch on AArch64 against a clean install of netbeans for jdk9 (including removingthe old project dirs) and it now seems to work ok. So, I believe the problems I was seeing before were to do with out of date data in the binary files and this patch is good to include.

### CODE REVIEW

**Comment by dougxc** [comment]
@adinn , now that https://github.com/graalvm/graal/commit/93772f94d9fc2e771f25d3b5a3cdc61ac6954663 has been merged, can you please rebase this PR on it to see if the Travis gate now passes. Sorry for the inconvenience.

**Comment by adinn** [comment]
Hi Doug. New PR has been posted at https://github.com/graalvm/graal/pull/223

**Comment by dougxc** [comment]
There is no need to close this PR and in general it's not a good idea as review continuity and context can be lost. Could you please (force) push your rebased changes to this PR.

**Comment by adinn** [comment]
On 07/06/17 14:10, Douglas Simon wrote:
> There is no need to close this PR and in general it's not a good idea as
> review continuity and context can be lost. Could you please (force) push
> your rebased changes to this PR.

I'm not really sure how I am supposed to do that. I am not an expert
wiht the use of github PRs. I only know how to create a PR from an
existing branch.

More to the point, I deleted the branch from which I cloned PR 222 in
order to upload the rebased branch on my local machine into the github
repo. The new PR 223 was created with reference to the new version of
the branch.

Is there some way I can rebase my local branch and then upload it into
the original branch in my github repo?

Is there some way I can associate the existing PR with the new branch I
have created?

regards,


Andrew Dinn
-----------
Senior Principal Software Engineer
Red Hat UK Ltd
Registered in England and Wales under Company Registration No. 03798903
Directors: Michael Cunningham, Michael ("Mike") O'Neill, Eric Shander

**Comment by tkrodriguez** [comment]
The normal practice is to use git pull --rebase to bring in the new changes and then use git push -f to push the rebased branch to github.  It's really no different than pushing additional changes apart from the -f option which says to replace the current HEAD with the new HEAD.  The PR just tracks the contents of the branch so whatever is in the branch is the contents of the PR.

**Comment by adinn** [comment]
Hmm, ok. Thanks for the tip.

So, given that I have nuked the branch that this PR was cloned from and then recreated it from is this PR still valid? Or is the new PR cloned from the new branch required?

**Comment by tkrodriguez** [comment]
The reopen button on this one is grayed out and a tooltip says it because there's already an open PR.  I tried closing the new one and then the tooltip changes to something about the branch being recreated but is still grayed out.  So I think we have to move to the new one.  We're not losing much in this case but in the future try and keep it within a single PR.  We can always help out with any git trickery required to make it work.

**Pull request closed without merging**
